/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import biz.Cliente;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author fabianra5789
 */
public class VCliente extends javax.swing.JFrame {
final String NOM_ARCHIVO = "Clientes.dat";
    //Gestionar los objetos dentro del formulario
    ArrayList<Object> objetos = new ArrayList<>();
    //Realizar la serialización y des-serialización de objetos
    //También llevar el listado
    Util util = new Util();

    //Gestionar el objeto actual
    //SE DEBE CAMBIAR EL TIPO DE OBJETO, en este caso es PUNTO.
    Cliente objeto;

    /**
    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        getObjetos(false, true, false);
        
        logo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
        txGuardar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salvar.png")));
        txNuevo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/agregar-archivo.png")));
        txCerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
        txBorrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/borrar.png")));
    }
private void getObjetos(boolean estNuevo, boolean estGuardar, boolean estBorrar) {

        //// SE DEBE MODIFICAR
        txNombre.setText("");
        txDocumento.setText("");
       
        txCodigo.setText("");
        txTelefono.setText("");
        //NO LO MODIFIQUE. solo renombre los botones en el formulario (jbBorrar, jbCerrar ......
        txNuevo.setText("Nuevo");
        txGuardar.setText("Guardar");
        txBorrar.setText("Borrar");
       

        //SE MODIFCA CON LA CLASE QUE SE ESTÉ TRABAJANDO, cambiar Punto() por dicha clase
        objeto = new Cliente();
        //Maquillaje NO MODIFICAR
        setEstadoBotones(estNuevo, estGuardar, estBorrar);

        //NO SE MODIFICA
        if (util.desSerializar(NOM_ARCHIVO) != null) {
            objetos = (ArrayList) util.desSerializar(NOM_ARCHIVO);
            // Modifica el título Puntos por el que corresponda
            String[] t = {"Listado de Clientes"};
            this.listado.setModel(new DefaultTableModel(util.setJTable(objetos), t));
        }
    }

private void setEstadoBotones(boolean estNuevo, boolean estGuardar, boolean estBorrar) {
        txNuevo.setEnabled(estNuevo);
        txGuardar.setEnabled(estGuardar);
        txBorrar.setEnabled(estBorrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txNuevo = new javax.swing.JButton();
        txBorrar = new javax.swing.JButton();
        txGuardar = new javax.swing.JButton();
        txCerrar = new javax.swing.JButton();
        txCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 16, 500, 360));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 397, 110));

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel5.setText("Clientes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, -1));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Hotel Manantial"));

        txNuevo.setText("Nuevo");
        txNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoActionPerformed(evt);
            }
        });

        txBorrar.setText("Borrar");
        txBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBorrarActionPerformed(evt);
            }
        });

        txGuardar.setText("Guardar");
        txGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGuardarActionPerformed(evt);
            }
        });

        txCerrar.setText("Cerrar");
        txCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCerrarActionPerformed(evt);
            }
        });

        txCodigo.setText("jTextField4");

        jLabel4.setText("Codigo:");

        txTelefono.setText("jTextField3");
        txTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefonoActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono:");

        txDocumento.setText("jTextField2");

        jLabel2.setText("Documento");

        txNombre.setText("jTextField1");
        txNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre y Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txCerrar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(64, 64, 64)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(txDocumento)
                    .addComponent(txTelefono)
                    .addComponent(txCodigo))
                .addGap(526, 526, 526))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNuevo)
                    .addComponent(txBorrar)
                    .addComponent(txGuardar)
                    .addComponent(txCerrar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoActionPerformed
        // TODO add your handling code here:
        getObjetos(false , true , false );
    }//GEN-LAST:event_txNuevoActionPerformed

    private void txBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBorrarActionPerformed
        // TODO add your handling code here:
         objetos.remove(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
    }//GEN-LAST:event_txBorrarActionPerformed

    private void txGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGuardarActionPerformed
        // TODO add your handling code here:
          
       objeto.setNombrePersona(txNombre.getText());
   
   objeto.setTipoDocumento(Integer.parseInt(txDocumento.getText()));
        objeto.setCodigoCliente(Integer.parseInt(txCodigo.getText()));
        objeto.setTelefono(Integer.parseInt(txTelefono.getText()));
        
   objetos.remove(objeto);
        objetos.add(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
        
    }//GEN-LAST:event_txGuardarActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        // TODO add your handling code here:
        objeto = (Cliente) this.listado.getValueAt(  listado.getSelectedRow(), 0);
        
        /////
        this.txNombre.setText(String.valueOf(objeto.getNombrePersona()));
        this.txCodigo.setText(String.valueOf(objeto.getCodigoCliente()));
        this.txTelefono.setText(String.valueOf(objeto.getTelefono()));
        this.txDocumento.setText(String.valueOf(objeto.getTipoDocumento()));
        
       
        setEstadoBotones(  true, true, true);
    }//GEN-LAST:event_listadoMouseClicked

    private void txTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefonoActionPerformed

    private void txCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txCerrarActionPerformed

    private void txNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    private javax.swing.JLabel logo;
    private javax.swing.JButton txBorrar;
    private javax.swing.JButton txCerrar;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txDocumento;
    private javax.swing.JButton txGuardar;
    private javax.swing.JTextField txNombre;
    private javax.swing.JButton txNuevo;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables
}
