/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import biz.Consumo;
import biz.Habitacion;
import biz.Huesped;
import biz.Productos;
import biz.Servicios;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author fabianra5789
 */
public class VHuesped extends javax.swing.JFrame {
final String NOM_ARCHIVO = "Huesped.dat";
    //Gestionar los objetos dentro del formulario
    ArrayList<Object> objetos = new ArrayList<>();
    //Realizar la serialización y des-serialización de objetos
    //También llevar el listado
    Util util = new Util();

    //Gestionar el objeto actual
    //SE DEBE CAMBIAR EL TIPO DE OBJETO, en este caso es PUNTO.
    Huesped objeto;
    /**
     * Creates new form VHuesped
     */
    public VHuesped() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        getObjetos(false, true, false );
        fhabitaciones.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/camas.png")));
        jLabel4.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
        txGuardar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salvar.png")));
        txNuevo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/agregar-archivo.png")));;
        txBorrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/borrar.png")));
        Cerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
    }
private void getObjetos(boolean estNuevo, boolean estGuardar, boolean estBorrar) {

        //// SE DEBE MODIFICAR
        txHuesped.setText("");
        txDocumento.setText("");
         txHabitacion.setText(""); 

        //NO LO MODIFIQUE. solo renombre los botones en el formulario (jbBorrar, jbCerrar ......
        txNuevo.setText("Nuevo");
        txGuardar.setText("Guardar");
        txBorrar.setText("Borrar");
        

        //SE MODIFCA CON LA CLASE QUE SE ESTÉ TRABAJANDO, cambiar Punto() por dicha clase
        objeto = new Huesped();
        //Maquillaje NO MODIFICAR
        setEstadoBotones(estNuevo, estGuardar, estBorrar);

        //NO SE MODIFICA
        if (util.desSerializar(NOM_ARCHIVO) != null) {
            objetos = (ArrayList) util.desSerializar(NOM_ARCHIVO);
            // Modifica el título Puntos por el que corresponda
            String[] t = {"Listado de puntos"};
            this.listado.setModel(new DefaultTableModel(util.setJTable(objetos), t));
        }
    }
private void setEstadoBotones(boolean estNuevo, boolean estGuardar, boolean estBorrar) {
        
        txNuevo.setEnabled(estNuevo);
        txGuardar.setEnabled(estGuardar);
        txBorrar.setEnabled(estBorrar);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txNuevo = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        txGuardar = new javax.swing.JButton();
        txBorrar = new javax.swing.JButton();
        txHuesped = new javax.swing.JTextField();
        txDocumento = new javax.swing.JTextField();
        txHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fhabitaciones = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setBackground(new java.awt.Color(191, 217, 215));
        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 16, 520, 320));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Huespedes Del Hotel Manantial"));

        txNuevo.setText("Nuevo");
        txNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoActionPerformed(evt);
            }
        });

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        txGuardar.setText("Guardar");
        txGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGuardarActionPerformed(evt);
            }
        });

        txBorrar.setText("Borrar");
        txBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBorrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Habitacion:");

        jLabel2.setText("Documento:");

        jLabel1.setText("Nombre huesped:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel5.setText("Huesped");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fhabitaciones.setText("Fotos");
        fhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhabitacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txHabitacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fhabitaciones)))
                .addGap(0, 605, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 370));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoActionPerformed
        // TODO add your handling code here:
          getObjetos(false , true , false );
           
    }//GEN-LAST:event_txNuevoActionPerformed

    private void txBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBorrarActionPerformed
        // TODO add your handling code here:
         objetos.remove(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
    }//GEN-LAST:event_txBorrarActionPerformed

    private void txGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGuardarActionPerformed
        // TODO add your handling code here:
        objeto.setDocumento(Integer.parseInt(txDocumento.getText()));
        objeto.setNombrePersona(txHuesped.getText());
        objetos.remove(objeto);
        objetos.add(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
    }//GEN-LAST:event_txGuardarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        // TODO add your handling code here:
         objeto = (Huesped) this.listado.getValueAt(listado.getSelectedRow(), 0);

        this.txHabitacion.setText(String.valueOf(objeto.getHabitaciones()));
        this.txHuesped.setText(String.valueOf(objeto.getNombrePersona()));
        this.txDocumento.setText(String.valueOf(objeto.getDocumento()));

        setEstadoBotones(true, true, true);
    }//GEN-LAST:event_listadoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
             
            view.vFk fk = new view.vFk(  this, "habitaciones.dat", "Listado de habitaciones del hotel", true);
            fk.setVisible(true);
            
            objeto.setHabitaciones((Habitacion) fk.getSeleccion().get(0));
            txHabitacion.setText( objeto.getHabitaciones().toString() );
            
        } catch (Exception ex) {
            Logger.getLogger(VConsumo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhabitacionesActionPerformed
        // TODO add your handling code here:
        VisorImagenHabitaciones imagenes = new VisorImagenHabitaciones();
                  imagenes.setVisible(true);
        
    }//GEN-LAST:event_fhabitacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton fhabitaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    private javax.swing.JButton txBorrar;
    private javax.swing.JTextField txDocumento;
    private javax.swing.JButton txGuardar;
    private javax.swing.JTextField txHabitacion;
    private javax.swing.JTextField txHuesped;
    private javax.swing.JButton txNuevo;
    // End of variables declaration//GEN-END:variables
}
