/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Ana Maria
 */
public class VInicio extends javax.swing.JFrame {

    /**
     * Creates new form VInicio
     */
    public VInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        Trabajadores.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/usuario-de-perfil.png")));
        foto.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/hotelito1.jpg")));
        Fotos.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/camara.png")));
        fHotel.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/foto.png")));
        mnarchivo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/carpeta.png")));
        mnayuda.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/herramientas-de-manitas.png")));
        txServicios.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/foto.png")));
        mnreservas.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/calendario.png")));
        mnsalir.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/cerrar.png")));
        mnhabitaciones.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/Habitaciones.png")));
        mnproductos.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/productos.png")));
        mnhabitaciones.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/Habitaciones.png")));
        mnconsumo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/consumo.png")));
        mnreserva.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/calendario.png")));
        mncliente.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/cliente.png")));
        mnhuesped.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/camas.png")));
        txInfo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/informacion.png")));
        Servicios.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/habitaciones.png")));

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        foto = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnarchivo = new javax.swing.JMenu();
        mnhabitaciones = new javax.swing.JMenuItem();
        mnproductos = new javax.swing.JMenuItem();
        Servicios = new javax.swing.JMenuItem();
        mnreservas = new javax.swing.JMenu();
        mnreserva = new javax.swing.JMenuItem();
        mncliente = new javax.swing.JMenuItem();
        mnhuesped = new javax.swing.JMenuItem();
        mnconsumo = new javax.swing.JMenuItem();
        Trabajadores = new javax.swing.JMenu();
        Fotos = new javax.swing.JMenu();
        fHotel = new javax.swing.JMenuItem();
        txServicios = new javax.swing.JMenuItem();
        mnayuda = new javax.swing.JMenu();
        txInfo = new javax.swing.JMenu();
        mnsalir = new javax.swing.JMenu();

        desktopPane.setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 800, 440));

        menuBar.setBackground(new java.awt.Color(191, 217, 215));
        menuBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio Hotel Manantial"));

        mnarchivo.setBackground(new java.awt.Color(191, 217, 215));
        mnarchivo.setMnemonic('e');
        mnarchivo.setText("Archivo");

        mnhabitaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnhabitaciones.setMnemonic('t');
        mnhabitaciones.setText("Habitaciones");
        mnhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhabitacionesActionPerformed(evt);
            }
        });
        mnarchivo.add(mnhabitaciones);

        mnproductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnproductos.setMnemonic('y');
        mnproductos.setText("Productos");
        mnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnproductosActionPerformed(evt);
            }
        });
        mnarchivo.add(mnproductos);

        Servicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Servicios.setText("Servicios");
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });
        mnarchivo.add(Servicios);

        menuBar.add(mnarchivo);

        mnreservas.setMnemonic('h');
        mnreservas.setText("Reservas");

        mnreserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnreserva.setMnemonic('c');
        mnreserva.setText("Reservas");
        mnreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnreservaActionPerformed(evt);
            }
        });
        mnreservas.add(mnreserva);

        mncliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mncliente.setMnemonic('a');
        mncliente.setText("Cliente");
        mncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnclienteActionPerformed(evt);
            }
        });
        mnreservas.add(mncliente);

        mnhuesped.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mnhuesped.setText("Huesped");
        mnhuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhuespedActionPerformed(evt);
            }
        });
        mnreservas.add(mnhuesped);

        mnconsumo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnconsumo.setMnemonic('p');
        mnconsumo.setText("Consumos");
        mnconsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnconsumoActionPerformed(evt);
            }
        });
        mnreservas.add(mnconsumo);

        menuBar.add(mnreservas);

        Trabajadores.setText("Trabajadores");
        Trabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajadoresMouseClicked(evt);
            }
        });
        menuBar.add(Trabajadores);

        Fotos.setText("Fotos");

        fHotel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fHotel.setText("Fotos Hotel");
        fHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHotelActionPerformed(evt);
            }
        });
        Fotos.add(fHotel);

        txServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        txServicios.setText("Fotos Servicios");
        txServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txServiciosActionPerformed(evt);
            }
        });
        Fotos.add(txServicios);

        menuBar.add(Fotos);

        mnayuda.setText("Ayuda");
        mnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnayudaMouseClicked(evt);
            }
        });
        menuBar.add(mnayuda);

        txInfo.setText("Info");
        txInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txInfoMouseClicked(evt);
            }
        });
        menuBar.add(txInfo);

        mnsalir.setText("Salir");
        mnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnsalirMouseClicked(evt);
            }
        });
        menuBar.add(mnsalir);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhabitacionesActionPerformed
        // TODO add your handling code here:
         VHabitacion habitaciones = new VHabitacion();
                  habitaciones.setVisible(true);
                 
    }//GEN-LAST:event_mnhabitacionesActionPerformed

    private void mnreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnreservaActionPerformed
        // TODO add your handling code here:
         VReserva reservas = new VReserva();
                  reservas.setVisible(true);
                 
    }//GEN-LAST:event_mnreservaActionPerformed

    private void mnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnproductosActionPerformed
        // TODO add your handling code here:
         VProductos productos = new VProductos();
                  productos.setVisible(true);
                 
    }//GEN-LAST:event_mnproductosActionPerformed

    private void mnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnclienteActionPerformed
        // TODO add your handling code here:
         VCliente clientes = new VCliente();
                  clientes.setVisible(true);
                 
    }//GEN-LAST:event_mnclienteActionPerformed

    private void mnhuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhuespedActionPerformed
        // TODO add your handling code here:
         VHuesped huespedes = new VHuesped();
                  huespedes.setVisible(true);
                 
    }//GEN-LAST:event_mnhuespedActionPerformed

    private void mnsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnsalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnsalirMouseClicked

    private void mnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnayudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contacte con el administrado por medio del siguiente correo electronico: eramireza1@ucentral.edu.co");
    }//GEN-LAST:event_mnayudaMouseClicked

    private void TrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajadoresMouseClicked
        // TODO add your handling code here:
         VTrabajador trabajadores = new VTrabajador();
                  trabajadores.setVisible(true);
    }//GEN-LAST:event_TrabajadoresMouseClicked

    private void txServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txServiciosActionPerformed
        // TODO add your handling code here:
        VisorImagenServicios imagenesS = new VisorImagenServicios();
                  imagenesS.setVisible(true);
    }//GEN-LAST:event_txServiciosActionPerformed

    private void txInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txInfoMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " correo electronico de contacto: manantial@yopmail.com");
    }//GEN-LAST:event_txInfoMouseClicked

    private void mnconsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnconsumoActionPerformed
        // TODO add your handling code here:
        VConsumo consumos = new VConsumo();
                  consumos.setVisible(true);
    }//GEN-LAST:event_mnconsumoActionPerformed

    private void fHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHotelActionPerformed
        // TODO add your handling code here:
        VisorImagenHotel hotu = new VisorImagenHotel();
                  hotu.setVisible(true);
    }//GEN-LAST:event_fHotelActionPerformed

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        // TODO add your handling code here:
        VServicios servicios = new VServicios();
                  servicios.setVisible(true);
    }//GEN-LAST:event_ServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Fotos;
    private javax.swing.JMenuItem Servicios;
    private javax.swing.JMenu Trabajadores;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem fHotel;
    private javax.swing.JLabel foto;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnarchivo;
    private javax.swing.JMenu mnayuda;
    private javax.swing.JMenuItem mncliente;
    private javax.swing.JMenuItem mnconsumo;
    private javax.swing.JMenuItem mnhabitaciones;
    private javax.swing.JMenuItem mnhuesped;
    private javax.swing.JMenuItem mnproductos;
    private javax.swing.JMenuItem mnreserva;
    private javax.swing.JMenu mnreservas;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu txInfo;
    private javax.swing.JMenuItem txServicios;
    // End of variables declaration//GEN-END:variables

}
