/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author fabianra5789
 */
public class VInicioCliente extends javax.swing.JFrame {

    /**
     * Creates new form VInicioCliente
     */
    public VInicioCliente() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        setResizable(false) ;
       
        foto.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/hotelito1.jpg")));
        Fotos.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/camara.png")));
        fHotel.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/foto.png")));
        txServicios.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/foto.png")));
        mnayuda.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/herramientas-de-manitas.png")));
        
        mnreservas.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/calendario.png")));
        mnsalir.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/cerrar.png")));
       txInfo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/informacion.png")));
        mnreserva.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/calendario.png")));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnreservas = new javax.swing.JMenu();
        mnreserva = new javax.swing.JMenuItem();
        Fotos = new javax.swing.JMenu();
        fHotel = new javax.swing.JMenuItem();
        txServicios = new javax.swing.JMenuItem();
        mnayuda = new javax.swing.JMenu();
        txInfo = new javax.swing.JMenu();
        mnsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio Hotel Manantial"));

        mnreservas.setMnemonic('h');
        mnreservas.setText("Reservas");

        mnreserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnreserva.setMnemonic('c');
        mnreserva.setText("Reservas");
        mnreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnreservaActionPerformed(evt);
            }
        });
        mnreservas.add(mnreserva);

        menuBar.add(mnreservas);

        Fotos.setText("Fotos");

        fHotel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fHotel.setText("Fotos Del Hotel");
        fHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fHotelMouseClicked(evt);
            }
        });
        fHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHotelActionPerformed(evt);
            }
        });
        Fotos.add(fHotel);

        txServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        txServicios.setText("Fotos Servicios");
        txServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txServiciosActionPerformed(evt);
            }
        });
        Fotos.add(txServicios);

        menuBar.add(Fotos);

        mnayuda.setText("Ayuda");
        mnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnayudaMouseClicked(evt);
            }
        });
        menuBar.add(mnayuda);

        txInfo.setText("Info");
        txInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txInfoMouseClicked(evt);
            }
        });
        menuBar.add(txInfo);

        mnsalir.setText("Salir");
        mnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnsalirMouseClicked(evt);
            }
        });
        menuBar.add(mnsalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnreservaActionPerformed
        // TODO add your handling code here:
        VReservasClientes reservas = new VReservasClientes();
        reservas.setVisible(true);

    }//GEN-LAST:event_mnreservaActionPerformed

    private void fHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fHotelMouseClicked
        // TODO add your handling code here:
        VisorImagenHabitaciones imagenes = new VisorImagenHabitaciones();
        imagenes.setVisible(true);
    }//GEN-LAST:event_fHotelMouseClicked

    private void fHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHotelActionPerformed
        // TODO add your handling code here:
        VisorImagenHotel hotelito = new VisorImagenHotel();
        hotelito.setVisible(true);
    }//GEN-LAST:event_fHotelActionPerformed

    private void mnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnayudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contacte con el administrado por medio del siguiente correo electronico: eramireza1@ucentral.edu.co");
    }//GEN-LAST:event_mnayudaMouseClicked

    private void mnsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnsalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnsalirMouseClicked

    private void txServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txServiciosActionPerformed
        // TODO add your handling code here:
         VisorImagenServicios imagenesS = new VisorImagenServicios();
                  imagenesS.setVisible(true);
    }//GEN-LAST:event_txServiciosActionPerformed

    private void txInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txInfoMouseClicked
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, " correo electronico de contacto: manantial@yopmail.com");
    }//GEN-LAST:event_txInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VInicioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Fotos;
    private javax.swing.JMenuItem fHotel;
    private javax.swing.JLabel foto;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnayuda;
    private javax.swing.JMenuItem mnreserva;
    private javax.swing.JMenu mnreservas;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu txInfo;
    private javax.swing.JMenuItem txServicios;
    // End of variables declaration//GEN-END:variables
}
