/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


 import javax.swing.ImageIcon;
import javax.swing.Timer;
/**
 *
 * @author Ana Maria
 */
public class VisorImagenHotel extends javax.swing.JFrame {
    ImageIcon Imagen[] = new ImageIcon[9];
    int contador = 1;
  
           
    
        
    
    /**
     * Creates new form ImagenesServicios
     */
    public VisorImagenHotel() {
        initComponents();
         this.setLocationRelativeTo(null);
        setResizable(false) ;
this.setTitle("Fotos Hotel Manantial");
txCerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
        for(int a =1; a<8; a++){
           Imagen[a] = new ImageIcon("/Users/fabianra5789/Documents/torrents/ima"+a+".jpg");
        }
        jLabel1.setIcon(Imagen[1]);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btizquierda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btderecha = new javax.swing.JButton();
        txCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(191, 217, 215));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 217, 215), 3, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 750, 470));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotos Del Hotel Manantial"));

        btizquierda.setText("Anterior");
        btizquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btizquierdaActionPerformed(evt);
            }
        });

        jButton1.setText("Automatico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btderecha.setText("Siguiente");
        btderecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btderechaActionPerformed(evt);
            }
        });

        txCerrar.setText("Cerrar");
        txCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btizquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(btderecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btderecha)
                    .addComponent(btizquierda))
                .addGap(32, 32, 32)
                .addComponent(txCerrar)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btizquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btizquierdaActionPerformed
        if(contador == 1){
            contador =9;
        }
        contador--;
        jLabel1.setIcon(Imagen[contador]);
    }//GEN-LAST:event_btizquierdaActionPerformed

    private void btderechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btderechaActionPerformed
        if(contador ==7){
            contador = 0;
        }
        contador ++;
        jLabel1.setIcon(Imagen[contador]);

    }//GEN-LAST:event_btderechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Timer timer = new Timer (1000, new ActionListener (){
            @Override
            public void actionPerformed(ActionEvent e) {
                jLabel1.setIcon(new javax.swing.ImageIcon("/Users/fabianra5789/Documents/torrents/ima"+contador+".jpg"));
                contador ++;
                if(contador ==9) contador = 1;
            }

        });
        timer.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCerrarActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_txCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorImagenHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorImagenHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorImagenHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorImagenHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorImagenHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btderecha;
    private javax.swing.JButton btizquierda;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txCerrar;
    // End of variables declaration//GEN-END:variables
}
