/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import biz.Usuario;
/**
 *
 * @author Ana Maria
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogueo
     */
    public VLogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        btloguearse.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/inicio.png")));
         txCerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
       imlogin.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
       btregistrarse.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/accesos.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imlogin = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        txContraseña = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btloguearse = new javax.swing.JButton();
        btregistrarse = new javax.swing.JButton();
        txCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("logueo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Hotel Manantial\n"));

        imlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelUsuario.setText("Usuario");

        txUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña");

        btloguearse.setText("Ingresar");
        btloguearse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloguearseActionPerformed(evt);
            }
        });

        btregistrarse.setText("Registrarse");
        btregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarseActionPerformed(evt);
            }
        });

        txCerrar.setText("Cerrar");
        txCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btloguearse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btregistrarse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txCerrar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(imlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(24, 24, 24)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btloguearse)
                    .addComponent(btregistrarse)
                    .addComponent(txCerrar))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsuarioActionPerformed

    private void btregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarseActionPerformed
  VRegistro abrir = new VRegistro();
  abrir.setVisible(true);
  this.dispose();
    }//GEN-LAST:event_btregistrarseActionPerformed
private void Trabajador(){
String usuario = txUsuario.getText();
        String paswd = txContraseña.getText();
    
    if(usuario.isEmpty() || paswd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Algún campo esta vacio");
            
        }else{
             if(usuario.equals("trabajador1") && paswd.equals("1234")){
                 JOptionPane.showMessageDialog(null,"Bienvenido");
                 VInicio inicio = new VInicio();
                  inicio.setVisible(true);
                 this.dispose();
                 
             }
        }


}

private void Cliente(){
String usuario = txUsuario.getText();
        String paswd = txContraseña.getText();
        
    if(usuario.isEmpty() || paswd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Algún campo esta vacio");
            
        }else{
             
             
             if(usuario.equals("cliente1") && paswd.equals("1234")){
                 JOptionPane.showMessageDialog(null,"Bienvenido");
                 VInicioCliente vistacliente = new VInicioCliente();
                  vistacliente.setVisible(true);
                 this.dispose();
                 
             
        }}

}
        
    private void btloguearseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloguearseActionPerformed
   String usuario= txUsuario.getText();
   String contraseña = txContraseña.getText();
   Trabajador();
   Cliente();
  int pos = Usuario.verificarLogueo(usuario, contraseña);
  if(pos ==-1){
          
  } else{
      VInicioCliente vistacliente = new VInicioCliente();
                  vistacliente.setVisible(true);
                 this.dispose();
  }
  
   
 
    
  
    }//GEN-LAST:event_btloguearseActionPerformed

    private void txCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txCerrarActionPerformed

    /**
     * @param args the command line arguments
     */

 public static void main(String[] args) {
     VLogin abrir = new VLogin();
     abrir.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btloguearse;
    private javax.swing.JButton btregistrarse;
    private javax.swing.JLabel imlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JButton txCerrar;
    private javax.swing.JTextField txContraseña;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
}
