/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import biz.Usuario;
import biz.ListaUsuario;
/**
 *
 * @author Ana Maria
 */
public class VRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRegistro
     */
    public VRegistro() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        btloguearse.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/inicio.png")));
         txCerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
       imlogin.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
    btregistrarse.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/accesos.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        txContraseña = new javax.swing.JTextField();
        btregistrarse = new javax.swing.JButton();
        btloguearse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imlogin = new javax.swing.JLabel();
        txCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("registro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 226, 80, -1));
        getContentPane().add(txUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 177, 200, -1));
        getContentPane().add(txContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 221, 200, -1));

        btregistrarse.setText("Registrarse");
        btregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, -1, 30));

        btloguearse.setText("loguearse");
        btloguearse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloguearseActionPerformed(evt);
            }
        });
        getContentPane().add(btloguearse, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 284, -1, 30));

        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 80, -1));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Hotel Manantial\n"));

        imlogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txCerrar.setText("Cerrar");
        txCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txCerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(txCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarseActionPerformed
        String usuario = txUsuario.getText();
        String contraseña = txContraseña.getText();
        String rango = txUsuario.getText();
        Usuario obj = new Usuario();
        if (Usuario.verificarUsuarioNuevo(usuario) ==-1) {

            obj.setNick(usuario);
            obj.setContraseña(contraseña);
            obj.setRango(rango);
            ListaUsuario.agregar(obj);
            JOptionPane.showMessageDialog(this, "SE REGISTRO CORRECTAMENTE");
        } else {
            JOptionPane.showMessageDialog(this, "ESTE USUARIO YA ESTA SIENDO USADO");
        }


    }//GEN-LAST:event_btregistrarseActionPerformed

    private void btloguearseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloguearseActionPerformed
      VLogin abrir = new VLogin();
      abrir.setVisible(true);
    }//GEN-LAST:event_btloguearseActionPerformed

    private void txCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txCerrarActionPerformed

    
     public static void main(String[] args) {
     VLogin abrir = new VLogin();
     abrir.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btloguearse;
    private javax.swing.JButton btregistrarse;
    private javax.swing.JLabel imlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txCerrar;
    private javax.swing.JTextField txContraseña;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
}
