/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;




import biz.Servicios;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author fabianra5789
 */
public class VServicios extends javax.swing.JFrame {
final String NOM_ARCHIVO = "servicios.dat";
    //Gestionar los objetos dentro del formulario
    ArrayList<Object> objetos = new ArrayList<>();
    //Realizar la serialización y des-serialización de objetos
    //También llevar el listado
    Util util = new Util();

    //Gestionar el objeto actual
    //SE DEBE CAMBIAR EL TIPO DE OBJETO, en este caso es PUNTO.
    Servicios objeto;

    /**
     * Creates new form Servicios
     */
    public VServicios() {
        initComponents();
        getObjetos(false, true, false);
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        jLabel4.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
        txGuardar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salvar.png")));
        txNuevo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/agregar-archivo.png")));
         txBorrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/borrar.png")));
        jButton4.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
    }
private void getObjetos(boolean estNuevo, boolean estGuardar, boolean estBorrar) {

        //// SE DEBE MODIFICAR
        txCosto.setText("");
        txServicio.setText("");
       
        txTipo.setText("");
        //NO LO MODIFIQUE. solo renombre los botones en el formulario (jbBorrar, jbCerrar ......
        txNuevo.setText("Nuevo");
        txGuardar.setText("Guardar");
        txBorrar.setText("Borrar");
       

        //SE MODIFCA CON LA CLASE QUE SE ESTÉ TRABAJANDO, cambiar Punto() por dicha clase
        objeto = new Servicios();
        //Maquillaje NO MODIFICAR
        setEstadoBotones(estNuevo, estGuardar, estBorrar);

        //NO SE MODIFICA
        if (util.desSerializar(NOM_ARCHIVO) != null) {
            objetos = (ArrayList) util.desSerializar(NOM_ARCHIVO);
            // Modifica el título Puntos por el que corresponda
            String[] t = {"Listado De Servicios"};
            this.listado.setModel(new DefaultTableModel(util.setJTable(objetos), t));
        }
    }
private void setEstadoBotones(boolean estNuevo, boolean estGuardar, boolean estBorrar) {
        txNuevo.setEnabled(estNuevo);
        txGuardar.setEnabled(estGuardar);
        txBorrar.setEnabled(estBorrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txGuardar = new javax.swing.JButton();
        txBorrar = new javax.swing.JButton();
        txNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txCosto = new javax.swing.JTextField();
        txTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 21, 620, 430));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios Del Hotel Manantial"));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txGuardar.setText("Guardar");
        txGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGuardarActionPerformed(evt);
            }
        });

        txBorrar.setText("Borrar");
        txBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBorrarActionPerformed(evt);
            }
        });

        txNuevo.setText("Nuevo");
        txNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del servicio:");

        jLabel2.setText("Costo:");

        txCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCostoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo De Servicio:");

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel5.setText("Servicios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(txBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(txGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNuevo)
                    .addComponent(txBorrar)
                    .addComponent(txGuardar)
                    .addComponent(jButton4))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoActionPerformed
        // TODO add your handling code here:
        getObjetos(false , true , false );
    }//GEN-LAST:event_txNuevoActionPerformed

    private void txBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBorrarActionPerformed
        // TODO add your handling code here:
        objetos.remove(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
    }//GEN-LAST:event_txBorrarActionPerformed

    private void txGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGuardarActionPerformed
        // TODO add your handling code here:
         objeto.setTipoServicio(txTipo.getText());
        objeto.setNombreServicio(txServicio.getText());
        objeto.setCosto(Integer.parseInt(txCosto.getText()));

        objetos.remove(objeto);
        objetos.add(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
        
    }//GEN-LAST:event_txGuardarActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        // TODO add your handling code here:
        objeto = (Servicios) this.listado.getValueAt(  listado.getSelectedRow(), 0);
        
        /////
        this.txTipo.setText(String.valueOf(objeto.getTipoServicio()));
        this.txServicio.setText(String.valueOf(objeto.getNombreServicio()));
        this.txCosto.setText(String.valueOf(objeto.getCosto()));
        
        setEstadoBotones(  true, true, true);
        
    }//GEN-LAST:event_listadoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    private javax.swing.JButton txBorrar;
    private javax.swing.JTextField txCosto;
    private javax.swing.JButton txGuardar;
    private javax.swing.JButton txNuevo;
    private javax.swing.JTextField txServicio;
    private javax.swing.JTextField txTipo;
    // End of variables declaration//GEN-END:variables
}
