/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import biz.Trabajador;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author fabianra5789
 */
public class VTrabajador extends javax.swing.JFrame {
final String NOM_ARCHIVO = "trabajadores.dat";
    //Gestionar los objetos dentro del formulario
    ArrayList<Object> objetos = new ArrayList<>();
    //Realizar la serialización y des-serialización de objetos
    //También llevar el listado
    Util util = new Util();

    //Gestionar el objeto actual
    //SE DEBE CAMBIAR EL TIPO DE OBJETO, en este caso es PUNTO.
    Trabajador objeto;

    /**
    /**
     * Creates new form VCliente
     */
    public VTrabajador() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false) ;
        
        logo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/logo.jpg")));
        txGuardar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salvar.png")));
        txNuevo.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/agregar-archivo.png")));
        txCerrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/salida.png")));
        txBorrar.setIcon(new javax.swing.ImageIcon(("/Users/fabianra5789/Documents/torrents/borrar.png")));
        getObjetos(false, true, false);
    }
private void getObjetos(boolean estNuevo, boolean estGuardar, boolean estBorrar) {

        //// SE DEBE MODIFICAR
        txNombre.setText("");
        txDocumento.setText("");
       
        txCodigo.setText("");
        txTelefono.setText("");
        //NO LO MODIFIQUE. solo renombre los botones en el formulario (jbBorrar, jbCerrar ......
        txNuevo.setText("Nuevo");
        txGuardar.setText("Guardar");
        txBorrar.setText("Borrar");
       

        //SE MODIFCA CON LA CLASE QUE SE ESTÉ TRABAJANDO, cambiar Punto() por dicha clase
        objeto = new Trabajador();
        //Maquillaje NO MODIFICAR
        setEstadoBotones(estNuevo, estGuardar, estBorrar);

        //NO SE MODIFICA
        if (util.desSerializar(NOM_ARCHIVO) != null) {
            objetos = (ArrayList) util.desSerializar(NOM_ARCHIVO);
            // Modifica el título Puntos por el que corresponda
            String[] t = {"Listado de Trabajadores"};
            this.listado.setModel(new DefaultTableModel(util.setJTable(objetos), t));
        }
    }

private void setEstadoBotones(boolean estNuevo, boolean estGuardar, boolean estBorrar) {
        txNuevo.setEnabled(estNuevo);
        txGuardar.setEnabled(estGuardar);
        txBorrar.setEnabled(estBorrar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txDocumento = new javax.swing.JTextField();
        txTelefono = new javax.swing.JTextField();
        txCodigo = new javax.swing.JTextField();
        txNuevo = new javax.swing.JButton();
        txBorrar = new javax.swing.JButton();
        txGuardar = new javax.swing.JButton();
        txCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(191, 217, 215));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre y Apellido:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, -1, -1));

        jLabel2.setText("Documento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, -1, -1));

        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 274, -1, -1));

        jLabel4.setText("Codigo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 318, -1, -1));

        txNombre.setText("jTextField1");
        getContentPane().add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 181, 319, -1));

        txDocumento.setText("jTextField2");
        getContentPane().add(txDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 225, 319, -1));

        txTelefono.setText("jTextField3");
        getContentPane().add(txTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 269, 319, -1));

        txCodigo.setText("jTextField4");
        getContentPane().add(txCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 313, 319, -1));

        txNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 345, -1, -1));

        txBorrar.setText("Borrar");
        txBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(txBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 345, -1, -1));

        txGuardar.setText("Guardar");
        txGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(txGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 345, -1, -1));

        txCerrar.setText("Cerrar");
        txCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(txCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 345, -1, -1));

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre y Apellido", "Documento", "Telefono", "Codigo"
            }
        ));
        listado.setColumnSelectionAllowed(true);
        listado.setRowHeight(30);
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);
        listado.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 22, 660, 360));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 500, 110));

        jPanel1.setBackground(new java.awt.Color(191, 217, 215));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajadores Hotel Manantial"));

        jLabel5.setFont(new java.awt.Font("Myanmar MN", 3, 24)); // NOI18N
        jLabel5.setText("Trabajadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 1020, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 342, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNuevoActionPerformed
        // TODO add your handling code here:
        getObjetos(false , true , false );
    }//GEN-LAST:event_txNuevoActionPerformed

    private void txBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBorrarActionPerformed
        // TODO add your handling code here:
         objetos.remove(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
    }//GEN-LAST:event_txBorrarActionPerformed

    private void txGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGuardarActionPerformed
        // TODO add your handling code here:
          
       objeto.setNombrePersona(txNombre.getText());
   
   objeto.setTipoDocumento(Integer.parseInt(txDocumento.getText()));
        objeto.setIdTrabajador(Integer.parseInt(txCodigo.getText()));
        objeto.setTelefono(Integer.parseInt(txTelefono.getText()));
        
   objetos.remove(objeto);
        objetos.add(objeto);
        util.serializar(NOM_ARCHIVO, objetos);
        getObjetos(false, true, false);
        
    }//GEN-LAST:event_txGuardarActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked
        // TODO add your handling code here:
        objeto = (Trabajador) this.listado.getValueAt(  listado.getSelectedRow(), 0);
        
        /////
        this.txNombre.setText(String.valueOf(objeto.getNombrePersona()));
        this.txCodigo.setText(String.valueOf(objeto.getIdPersona()));
        this.txTelefono.setText(String.valueOf(objeto.getTelefono()));
        this.txDocumento.setText(String.valueOf(objeto.getTipoDocumento()));
        
       
        setEstadoBotones(  true, true, true);
    }//GEN-LAST:event_listadoMouseClicked

    private void txCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado;
    private javax.swing.JLabel logo;
    private javax.swing.JButton txBorrar;
    private javax.swing.JButton txCerrar;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txDocumento;
    private javax.swing.JButton txGuardar;
    private javax.swing.JTextField txNombre;
    private javax.swing.JButton txNuevo;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables
}
